menu:
    Blog: /
    Archive: /archives/
    # Weibo: http://weibo.com/yakomoz
    GitHub: https://github.com/pampang
    # Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-101877487-2

# Copyright Infomation
startyear: 2015
